#!/usr/bin/env python3
"""Produce descriptive statistics for the trading dataset."""


def analyze(df):
    """
    Compute descriptive stats for every column except `Timestamp`.

    Parameters
    ----------
    df : pandas.DataFrame
        Input market data potentially containing a `Timestamp` column.

    Returns
    -------
    pandas.DataFrame
        Descriptive statistics generated by `DataFrame.describe()` on all
        columns except `Timestamp`.
    """
    data = df.copy()
    if 'Timestamp' in data.columns:
        data = data.drop(columns=['Timestamp'])

    return data.describe()
